"""
Centralized CSS used by Gradio Blocks.
"""

CSS_GLOBAL = (
    "footer {visibility: hidden}\n"
    "#chat_interface .wrapper,\n"
    "#chat_interface .wrapper.svelte-g3p8na {\n"
    "  scroll-behavior: auto !important;\n"
    "  overscroll-behavior: contain;\n"
    "}\n"
    "#chat_interface .bubble-wrap,\n"
    "#chat_interface .bubble-wrap.svelte-gjtrl6 {\n"
    "  scroll-behavior: auto !important;\n"
    "}\n"
    "#chat_interface .wrapper * { overflow-anchor: none; }\n"
    "/* Hide Chatbot clear/trash icon inside the main chat */\n"
    "#chat_interface button[aria-label*='clear' i],\n"
    "#chat_interface button[title*='clear' i],\n"
    "#chat_interface button[aria-label*='delete' i],\n"
    "#chat_interface button[title*='delete' i] {\n"
    "  display: none !important;\n"
    "}\n"
    "/* Per-button icon sizing: target the <img> inside each button by elem_id */\n"
    "#btn_chatgpt .icon, #btn_chatgpt img { height: 22px !important; width: auto; }\n"
    "#btn_claude .icon, #btn_claude img { height: 22px !important; width: auto; }\n"
    "#btn_gemini .icon, #btn_gemini img { height: 22px !important; width: auto; }\n"
    "#btn_chatgpt_gemini .icon, #btn_chatgpt_gemini img { height: 24px !important; width: auto; }\n"
    "#btn_all .icon, #btn_all img { height: 25px !important; width: auto; position: relative; top: -2.5px; }\n"
    "/* New Chat button: position in top-right over tab row without taking space */\n"
    "#btn_new_chat { position: absolute; top: 6px; right: 12px; z-index: 1000; width: auto; display: inline-block; }\n"
    "#btn_new_chat button { width: auto !important; min-width: 110px; height: 32px; line-height: 24px; padding: 4px 12px; }\n"
    "/* Active button state - orange background when process is running */\n"
    "#btn_chatgpt[data-active='true'],\n"
    "#btn_claude[data-active='true'],\n"
    "#btn_gemini[data-active='true'],\n"
    "#btn_chatgpt_gemini[data-active='true'],\n"
    "#btn_all[data-active='true'] {\n"
    "  background-color: #ff8c00 !important; /* orange background */\n"
    "  color: white !important; /* white text for contrast */\n"
    "  border-color: #ff8c00 !important; /* orange border */\n"
    "}\n"
    "/* Ensure hover states still work for active buttons */\n"
    "#btn_chatgpt[data-active='true']:hover,\n"
    "#btn_claude[data-active='true']:hover,\n"
    "#btn_gemini[data-active='true']:hover,\n"
    "#btn_chatgpt_gemini[data-active='true']:hover,\n"
    "#btn_all[data-active='true']:hover {\n"
    "  background-color: #e07600 !important; /* slightly darker orange on hover */\n"
    "  border-color: #e07600 !important;\n"
    "}\n"
    "/* Hide the stop icon reference button */\n"
    "#hidden_stop_icon_btn {\n"
    "  display: none !important;\n"
    "}\n"
    "/* Confirmation overlay for New Chat */\n"
    "#confirm_overlay {\n"
    "  position: fixed;\n"
    "  inset: 0;\n"
    "  background: rgba(0,0,0,0.45);\n"
    "  display: flex;\n"
    "  align-items: center;\n"
    "  justify-content: center;\n"
    "  z-index: 2000;\n"
    "}\n"
    "#confirm_overlay.svelte-18eozq0 { display: flex !important; }\n"
    "#confirm_modal {\n"
    "  background: #fff;\n"
    "  border-radius: 8px;\n"
    "  box-shadow: 0 8px 30px rgba(0,0,0,0.25);\n"
    "  width: min(560px, 92vw);\n"
    "  padding: 2px;\n"
    "}\n"
    "/* Gradio's gr-group has an inner div wrapper. Style this for a rounded content area. */\n"
    "#confirm_modal > div {\n"
    "  border-radius: 6px;\n"
    "  overflow: hidden;\n"
    "  padding: 16px;\n"
    "}\n"
    "#confirm_modal .prose, #confirm_modal p, #confirm_modal .markdown {\n"
    "  padding: 0;\n"
    "  margin: 0 0 12px 0;\n"
    "}\n"
    "#confirm_modal .gr-row {\n"
    "  padding: 0;\n"
    "  margin: 0;\n"
    "  gap: 8px;\n"
    "  justify-content: flex-end;\n"
    "}\n"
    "#confirm_modal > .gr-group,\n"
    "#confirm_modal > .gr-row,\n"
    "#confirm_modal > .gr-column,\n"
    "#confirm_modal > .gr-box,\n"
    "#confirm_modal > .gr-form {\n"
    "  margin: 0 !important;\n"
    "  padding: 0 !important;\n"
    "  background: transparent !important;\n"
    "  border: none !important;\n"
    "  box-shadow: none !important;\n"
    "}\n"
)


