"""
Centralized CSS used by Gradio Blocks.
"""

CSS_GLOBAL = (
    "footer {visibility: hidden}\n"
    "#chat_interface .wrapper,\n"
    "#chat_interface .wrapper.svelte-g3p8na {\n"
    "  scroll-behavior: auto !important;\n"
    "  overscroll-behavior: contain;\n"
    "}\n"
    "#chat_interface .bubble-wrap,\n"
    "#chat_interface .bubble-wrap.svelte-gjtrl6 {\n"
    "  scroll-behavior: auto !important;\n"
    "}\n"
    "#chat_interface .wrapper * { overflow-anchor: none; }\n"
    "/* Hide Chatbot clear/trash icon inside the main chat */\n"
    "#chat_interface button[aria-label*='clear' i],\n"
    "#chat_interface button[title*='clear' i],\n"
    "#chat_interface button[aria-label*='delete' i],\n"
    "#chat_interface button[title*='delete' i] {\n"
    "  display: none !important;\n"
    "}\n"
    "/* Per-button icon sizing: target the <img> inside each button by elem_id */\n"
    "#btn_chatgpt .icon, #btn_chatgpt img { height: 22px !important; width: auto; }\n"
    "#btn_claude .icon, #btn_claude img { height: 22px !important; width: auto; }\n"
    "#btn_gemini .icon, #btn_gemini img { height: 22px !important; width: auto; }\n"
    "#btn_chatgpt_gemini .icon, #btn_chatgpt_gemini img { height: 24px !important; width: auto; }\n"
    "#btn_all .icon, #btn_all img { height: 25px !important; width: auto; position: relative; top: -2.5px; }\n"
    "/* New Chat button: position in top-right over tab row without taking space */\n"
    "#btn_new_chat { position: absolute; top: 6px; right: 12px; z-index: 1000; width: auto; display: inline-block; }\n"
    "#btn_new_chat button { width: auto !important; min-width: 110px; height: 32px; line-height: 24px; padding: 4px 12px; }\n"
    "/* Active button state - orange background when process is running */\n"
    "#btn_chatgpt[data-active='true'],\n"
    "#btn_claude[data-active='true'],\n"
    "#btn_gemini[data-active='true'],\n"
    "#btn_chatgpt_gemini[data-active='true'],\n"
    "#btn_all[data-active='true'] {\n"
    "  background-color: #ff8c00 !important; /* orange background */\n"
    "  color: white !important; /* white text for contrast */\n"
    "  border-color: #ff8c00 !important; /* orange border */\n"
    "}\n"
    "/* Ensure hover states still work for active buttons */\n"
    "#btn_chatgpt[data-active='true']:hover,\n"
    "#btn_claude[data-active='true']:hover,\n"
    "#btn_gemini[data-active='true']:hover,\n"
    "#btn_chatgpt_gemini[data-active='true']:hover,\n"
    "#btn_all[data-active='true']:hover {\n"
    "  background-color: #e07600 !important; /* slightly darker orange on hover */\n"
    "  border-color: #e07600 !important;\n"
    "}\n"
    "/* Hide the stop icon reference button */\n"
    "#hidden_stop_icon_btn {\n"
    "  display: none !important;\n"
    "}\n"
)


